format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$cmd_duration $jobs\
[\uE0B6](fg:#313244)\
$time\
$line_break\
$character"""

[character]
success_symbol = "[=>](bold green)"
error_symbol = "[X](bold red)[>](bold green)"

[cmd_duration]
style = "yellow"

[directory]
read_only = "󰉐 "
truncation_symbol = "…/"

[time]
disabled = false
format = "[$time]($style)"
style = "fg:#A6E3A1 bg:#313244"
